import type { Metadata } from "next";
import "./globals.css";
import members from "./webring/membership-lists/default";
import WebringAutoNavigate from "./webring/components/webring-auto-navigate";
import { Suspense } from "react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      
      <body className="min-h-full flex flex-col">
        <Suspense>
          <WebringAutoNavigate membersJSON={JSON.stringify(members)} />
        </Suspense>
        {children}
      </body>
    </html>
  );
}
