import { BookringMember } from "../bookring-member";
import { Member } from "../members"

const members: Member[] = [
    new BookringMember("Nikhila's site", 
        new URL("http://localhost:3000/"), 
        new URL("images/book_covers/the_yellow_wallpaper.jpg", "http://localhost:3000/"),
        "The Yellow Wallpaper by Charlotte Perkins Stetson", 
        new URL("https://www.goodreads.com/book/show/235789141-the-yellow-wall-paper")),
    new BookringMember("site 2",
        new URL("https://bing1.com"),
        new URL("images/book_covers/they_lost_their_heads.jpg", "http://localhost:3000/"),
        "They Lost Their Heads! by Carlyn Beccia",
        new URL("https://www.goodreads.com/en/book/show/25663883-they-lost-their-heads")),
    new BookringMember("site 3",
        new URL("https://bing2.com"),
        new URL("images/book_covers/to_live.jpg", "http://localhost:3000/"),
        "To Live by Yu Hua", 
        new URL("https://www.goodreads.com/book/show/334971.To_Live")),
    new BookringMember("site 4",
        new URL("https://bing3.com"),
        new URL("images/book_covers/das_kapital.jpg", "http://localhost:3000/"),
        "Das Kapital by Karl Marx",
        new URL("https://www.goodreads.com/book/show/238953.Das_Kapital")),
    new BookringMember("site 5",
        new URL("https://bing4.com"),
        new URL("images/book_covers/send_you_a_bullet.jpg", "http://localhost:3000/"),
        "Send You A Bullet by Liu Yu",
        new URL("https://www.goodreads.com/book/show/72212474-send-you-a-bullet")),
    new BookringMember("site 6",
        new URL("https://bing5.com"),
        new URL("images/book_covers/2001_a_space_odyssey.jpg", "http://localhost:3000/"),
        "2001: A Space Odyssey by Arthur C.Clarke",
        new URL("https://www.goodreads.com/book/show/70535.2001")),
    new BookringMember("site 7",
        new URL("https://bing6.com"),
        new URL("images/book_covers/sophies_world.jpg", "http://localhost:3000/"),
        "Sophie’s World by Jostein Gaarder",
        new URL("https://www.goodreads.com/en/book/show/10959.Sophie_s_World")),
    new BookringMember("site 8",
        new URL("https://bing7.com"),
        new URL("images/book_covers/foundation.jpg", "http://localhost:3000/"),
        "Foundation by Isaac Asimov",
        new URL("https://www.goodreads.com/en/book/show/29579.Foundation")),
];

export default members;