import { BookringMember } from "../bookring-member";
import { Member } from "../members"

const members: Member[] = [
    new BookringMember("Nikhila's site", 
        new URL("https://nikhilagurusinghe.github.io/bookring/"), 
        new URL("images/book_covers/the_yellow_wallpaper.jpg", process.env.PAGES_BASE_PATH),
        "The Yellow Wallpaper by Charlotte Perkins Stetson", 
        new URL("https://www.goodreads.com/book/show/235789141-the-yellow-wall-paper")),
    new BookringMember("site 2",
        new URL("https://nikhilagurusinghe.github.io/bookring/?1"),
        new URL("images/book_covers/they_lost_their_heads.jpg", process.env.PAGES_BASE_PATH),
        "They Lost Their Heads! by Carlyn Beccia",
        new URL("https://www.goodreads.com/en/book/show/25663883-they-lost-their-heads")),
    new BookringMember("site 3",
        new URL("https://nikhilagurusinghe.github.io/bookring/?2"),
        new URL("images/book_covers/to_live.jpg", process.env.PAGES_BASE_PATH),
        "To Live by Yu Hua", 
        new URL("https://www.goodreads.com/book/show/334971.To_Live")),
    new BookringMember("site 4",
        new URL("https://nikhilagurusinghe.github.io/bookring/?3"),
        new URL("images/book_covers/das_kapital.jpg", process.env.PAGES_BASE_PATH),
        "Das Kapital by Karl Marx",
        new URL("https://www.goodreads.com/book/show/238953.Das_Kapital")),
    new BookringMember("site 5",
        new URL("https://nikhilagurusinghe.github.io/bookring/?4"),
        new URL("images/book_covers/send_you_a_bullet.jpg", process.env.PAGES_BASE_PATH),
        "Send You A Bullet by Liu Yu",
        new URL("https://www.goodreads.com/book/show/72212474-send-you-a-bullet")),
    new BookringMember("site 6",
        new URL("https://nikhilagurusinghe.github.io/bookring/?5"),
        new URL("images/book_covers/2001_a_space_odyssey.jpg", process.env.PAGES_BASE_PATH),
        "2001: A Space Odyssey by Arthur C.Clarke",
        new URL("https://www.goodreads.com/book/show/70535.2001")),
    new BookringMember("site 7",
        new URL("https://nikhilagurusinghe.github.io/bookring/?6"),
        new URL("images/book_covers/sophies_world.jpg", process.env.PAGES_BASE_PATH),
        "Sophie’s World by Jostein Gaarder",
        new URL("https://www.goodreads.com/en/book/show/10959.Sophie_s_World")),
    new BookringMember("site 8",
        new URL("https://nikhilagurusinghe.github.io/bookring/?7"),
        new URL("images/book_covers/foundation.jpg", process.env.PAGES_BASE_PATH),
        "Foundation by Isaac Asimov",
        new URL("https://www.goodreads.com/en/book/show/29579.Foundation")),
];

export default members;